spring:
  application:
    name: llongaiagent
#  datasource:
#    url: jdbc:postgresql://tzl-ai-rag-pg.pg.polardb.rds.aliyuncs.com:5432/tzl
#    username: my_root
#    password: 2534838591@asd
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-deade061011c4aa0ba64f594c0cdbd27
      chat:
        options:
          model: qwen-max
      embedding:
        options:
          model: text-embedding-v3
    mcp:
      client:
        enabled: true
        sse:
          connections:
            server1:
              url: http://localhost:8127/sse
        # 以下是 本地mcp的配置
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
#          request-timeout: 60s        # 给足时间
#          connect-timeout: 10s        # 连接/启动超时（如果有此配置）
    vectorstore:
      pgvector:
      index-type: HNSW #索引类型
      distance-type: COSINE_DISTANCE
      dimensions: 1024 # 向量字段的维度
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

  # springdoc-openapi 接口文档项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # 修改一下路径，把controller的包的路径写在下面
      packages-to-scan: com.tzl.llongaiagent.controller
  # knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8080
  servlet:
    context-path: /api
searchAPi:
  apiKey: i2Grugyg9RpYS6SeRDipcwtW

# 官方的标准,但是丧失了灵活性，我们自定义一个
# 你想改变哪个类的打印级别，就直接把org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug换成那个详细的类即可
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug